### ISSUE TITLE
Widgets on the dashboard, where "Pending jobs" is the most crucial

### ISSUE THREAD

**Issue by elofu17** [spotify/puppetexplorer#54]
In config.js(.example), please add something like this (I'm no programmer but I think you get the idea):

```
DASHBOARD_PANELS = [
  {"name":"Nodes with failures","type":"danger","query":"#node.latest_report_status=\"failed\""},
  {"name":"Nodes with pending jobs","type":"warning","query":"<insert the same query that generate the blue icons>"},
  {"name":"Unresponsive nodes (last ${UNRESPONSIVE_HOURS}h)","type":"danger","query":"#node.report_timestamp < @\"now - $UNRESPONSIVE_HOURS hours\""},
  {"name":"Nodes in production env","type":"success","query":"#node.catalog_environment = production"},
  {{"name":"Nodes in non-production env",type:"warning",query:"#node.catalog_environment != production"}}
];
```

1)
I have cron run 'puppet agent -t --noop' every now and then on all my nodes.
Normally these noops show up as grey icons in the Nodes tab in Puppet Explorer, as there's nothing to do. The nodes are up to date. Everything is good.

However, if the noop discover pending changes, this is indicated with a blue icon in the Node tab.
It is crucial to me to have this as a dashboard widget, as it will show how many nodes aren't up to date.

(
Since it should be possible to click on the widget to list the matching nodes, its query must be compatible with the node-puppetdbquery syntax.
I haven't managed to create such query (I gave up since 'node-puppetdbquery' bail on queries with a questionmark in them, like "#report.latest_report?=true" (see separate bug report)).
But I guess the query should look something like this:
#report { latest_report?=true and noop=true and status="unchanged" }
Or perhaps you can do something like "#node.latest_report_status="unchanged" and not <reports with no events>". The "unchanged" will match on both grey and blue nodes and then we filter out the ones with empty reports = only blue left.
Oh, well, you're the programmer. You'll figure something out. :)
)

2)
In the 'Unresponsive nodes' widget you're using a static query:
'#node.report_timestamp < @"now - 2 hours"'
This forces the widget to 2 hours even though the user has configured UNRESPONSIVE_HOURS to e.g. 24 earlier in the file.
Update to something like this: '#node.report_timestamp < @"now - $UNRESPONSIVE_HOURS hours"'

3)
Overkill, but just a simple if-statement:
If puppetdb only deal with one single environment ("production"), you could hide the 'Nodes in non-production env' widget from the dashboard, since it will always show "0" anyhow.

**Comment by elofu17** [comment]
Updated the text above a bit after https://github.com/dalen/node-puppetdbquery/issues/1 was updated.

**Comment by elofu17** [comment]
Update:
Since the latest update of the puppet agent software (and puppetdb 4.2), we now have a new keyword for finding nodes with pending jobs: noop_pending=true.

So I've modified the original text with:
 old: {"name":"Nodes with pending jobs","type":"warning","query":"#report { latest_report?=true and noop=true and status=\"unchanged\" }"},
 new: {"name":"Nodes with pending jobs","type":"warning","query":"#report { latest_report?=true and noop_pending=true }"},

**Comment by Loshea** [comment]
I have tried messing around with this some, and am finding that PE apparently doesn't understand latest_report?.  When I try to query on it, Chrome reports:
`app.js:58 Error: Lexical error on line 1. Unrecognized text.
...report.latest_report?=true and noop_pend
-----------------------^
    at Parser.parseError (https://pe.vmlapps.com/app.js:107:5439)
    at Object.parseError (https://pe.vmlapps.com/app.js:107:7768)
    at Object.next (https://pe.vmlapps.com/app.js:107:11776)
    at Object.lex (https://pe.vmlapps.com/app.js:107:11943)
    at b (https://pe.vmlapps.com/app.js:107:5515)
    at Parser.parse (https://pe.vmlapps.com/app.js:107:6207)
    at Object.process.undefined.require.undefined.exports.parse (https://pe.vmlapps.com/app.js:107:13987)
    at Object.exports.parse (https://pe.vmlapps.com/app.js:103:218)
    at PuppetDB.parse (https://pe.vmlapps.com/app.js:26:1011)
    at PuppetDB.parseAndQuery (https://pe.vmlapps.com/app.js:26:1447) <div class="container-fluid ng-scope ng-enter" ng-view="" data-ng-animate="1" style="transition-delay: -9999s;">`

**Comment by Loshea** [comment]
looks like it was fixed in node-puppetdbquery
https://github.com/dalen/node-puppetdbquery/blob/master/lib/parser.jison

does this project depend on node-puppetdbquery?

**Comment by elofu17** [comment]
Yes, I bug-reported it in node-puppetdbquery.
Yes, PuppetExplorer depend on it.
